### PR TITLE
NEW Ability to synchronize scrolling between panes

### PR DESCRIPTION
**Pull request by patricknelson**
This feature is easily configurable via checkbox positioned between the two scrolling panes. This is a huge convenience for folks like me... what do you think? Check it out!

### CODE REVIEW

**Comment by patricknelson** [comment]
Oh -- some of my debug code has creeped in. Maybe we could standardize the implementation of the developer tools (F12 on windows). What do you think of that? Also, I did a few other things not outlined in the main post:

- Added `.editorconfig` to standardize formatting (my defaults vary from yours, etc).
- Using jQuery's document ready event since I'm using jQuery selectors on load.
- I didn't use the `onclick` attrib, instead I'm using jQuery's `on()`/`off()` event listeners.

**Comment by patricknelson** [comment]
Also forgot to mention that I wrapped the radio text so that it's also clickable (better UI/UX, IMHO).

**Comment by amitmerchant1990** [comment]
Hey @patricknelson These are really nice improvements. Sync-scrolling is definitely a great addition. I'm merging the pull request. Thanks! 👍

**Comment by patricknelson** [comment]
No problem! It's such a great feature for me, once I've used it I was spoiled, so I felt it made sense to implement since it was easy... I think it's a great feature to advertise, so I wonder if an updated version of the demo GIF should be made which quickly shows the synchronized scrolling?

**Comment by amitmerchant1990** [comment]
Yes @patricknelson, we should definitely recreate the demo GIF which depicts all the things including this feature altogether. I'll create one and will keep you posted about it. 😃

**Comment by amitmerchant1990** [comment]
@patricknelson FYI : Added new demo GIF which depicts all newly added and legacy features altogether. 🎉

**Pull request merged**
